/*
	TCP 'Hello' server
*/

#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/socket.h> // Socket-related functions
#include <netinet/in.h> // Socket structs
#include <string.h> 	// bzero()
#include <unistd.h> 	// close()
#include <arpa/inet.h> 	// inet_ntoa()

#define ERROR -1
char msg[] = "Hello there! This message was generated by this server!\n";

void _error(char* msg)
{
	perror(msg);
	exit(-1);
}

int main(int argc, char* argv[])
{
	if(argc < 2)
	{
		printf("Usage: ./helloserver [port]\n");
		exit(-1);
	}

	int sock, cli; // Socket descripters
	struct sockaddr_in server, client; // Ip for server and client
	int sockaddr_in_length = sizeof(struct sockaddr_in);

	sock = socket(AF_INET, SOCK_STREAM, 0); // Get discriptor from kernal
	if(sock == ERROR) _error("problem getting socket discriptor: ");

	server.sin_family = AF_INET;
	server.sin_port = htons(atoi(argv[1])); // Convert to network order
	server.sin_addr.s_addr = INADDR_ANY; 	// Server address is all ips on machine
	bzero(&server.sin_zero, 8); 			// Zero-out the padding in struct

	if(bind(sock, (struct sockaddr*) &server, sockaddr_in_length) == ERROR)
		_error("couldnt bind: "); // Bind server address info to socket
	
	if(listen(sock, 5) == ERROR) _error("listening error:"); // Start listening

	while(1) // Loop through available clients
	{	
		cli = accept(sock, (struct sockaddr*) &client, &sockaddr_in_length);
		if(cli == ERROR) _error("client socket error: ");
		// Send message!
		int sent = send(cli, msg, sizeof(msg), 0);
		printf("sent %d bytes to %s\n", sent, inet_ntoa(client.sin_addr));
		close(cli);
	}
	return 0;
}
